t5-base:
  epochs: 50
  batch_size: 32
  learning_rate: 1e-4
  weight_decay_rate: 0.01
  max_length: 128
  padding: 'max_length'
  truncation: 'longest_first'
  num_workers: 0
t5-large:
  epochs: 30 
  batch_size: 8
  learning_rate: 5e-5
  weight_decay_rate: 0.01
  max_length: 128
  padding: 'max_length'
  truncation: 'longest_first'
  num_workers: 0
